### PR TITLE
Working beta server

### PR DESCRIPTION
**Pull request by ashtonkellis**

### CODE REVIEW

**Review by GoldBeardSea — APPROVED** [review]

**Review by GoldBeardSea — APPROVED** [review]

**Comment by kgamer007** [comment]
I have reviewed the server.js. It's ready to merge.

**Review by kgamer007 — APPROVED** [review]
Ashton added the 'random' api. I have reviewed the changes. It's ready to merge.

**Review by SamPG2017 — APPROVED** [review]
Changes look good to me.

**Review by kgamer007 — APPROVED** [review]
It's good to go for a merge.

**Review by kgamer007 — APPROVED** [review]
changes look similar from other commit.

**Pull request merged**
